/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/gl-ionic2-env-configuration.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '../../src/providers/env-configuration-provider';
import * as import7 from '@angular/core/src/application_init';
import * as import8 from '@angular/core/src/testability/testability';
import * as import9 from '@angular/core/src/application_ref';
import * as import10 from '@angular/core/src/linker/compiler';
import * as import11 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import12 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import13 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import14 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from '@angular/core/src/animation/animation_queue';
import * as import17 from '@angular/core/src/linker/view_utils';
import * as import18 from '@angular/platform-browser/src/browser/title';
import * as import19 from '@angular/core/src/di/injector';
import * as import20 from '@angular/core/src/i18n/tokens';
import * as import21 from '@angular/core/src/application_tokens';
import * as import22 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import23 from '@angular/platform-browser/src/dom/events/key_events';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import26 from '@angular/core/src/console';
import * as import27 from '@angular/core/src/error_handler';
import * as import28 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import29 from '@angular/platform-browser/src/dom/animation_driver';
import * as import30 from '@angular/core/src/render/api';
import * as import31 from '@angular/core/src/security';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class GLIonic2EnvConfigurationModuleInjector extends import0.NgModuleInjector<import1.GLIonic2EnvConfigurationModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _GLIonic2EnvConfigurationModule_3:import1.GLIonic2EnvConfigurationModule;
  __LOCALE_ID_4:any;
  __NgLocalization_5:import5.NgLocaleLocalization;
  _ErrorHandler_6:any;
  _EnvConfigurationProvider_7:import6.EnvConfigurationProvider;
  _APP_INITIALIZER_8:any[];
  _ApplicationInitStatus_9:import7.ApplicationInitStatus;
  _Testability_10:import8.Testability;
  _ApplicationRef__11:import9.ApplicationRef_;
  __ApplicationRef_12:any;
  __Compiler_13:import10.Compiler;
  __APP_ID_14:any;
  __DOCUMENT_15:any;
  __HAMMER_GESTURE_CONFIG_16:import11.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_17:any[];
  __EventManager_18:import12.EventManager;
  __DomSharedStylesHost_19:import13.DomSharedStylesHost;
  __AnimationDriver_20:any;
  __DomRootRenderer_21:import14.DomRootRenderer_;
  __RootRenderer_22:any;
  __DomSanitizer_23:import15.DomSanitizerImpl;
  __Sanitizer_24:any;
  __AnimationQueue_25:import16.AnimationQueue;
  __ViewUtils_26:import17.ViewUtils;
  __IterableDiffers_27:any;
  __KeyValueDiffers_28:any;
  __SharedStylesHost_29:any;
  __Title_30:import18.Title;
  constructor(parent:import19.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LOCALE_ID_4():any {
    if ((this.__LOCALE_ID_4 == null)) { (this.__LOCALE_ID_4 = import3._localeFactory(this.parent.get(import20.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_4;
  }
  get _NgLocalization_5():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import5.NgLocaleLocalization(this._LOCALE_ID_4)); }
    return this.__NgLocalization_5;
  }
  get _ApplicationRef_12():any {
    if ((this.__ApplicationRef_12 == null)) { (this.__ApplicationRef_12 = this._ApplicationRef__11); }
    return this.__ApplicationRef_12;
  }
  get _Compiler_13():import10.Compiler {
    if ((this.__Compiler_13 == null)) { (this.__Compiler_13 = new import10.Compiler()); }
    return this.__Compiler_13;
  }
  get _APP_ID_14():any {
    if ((this.__APP_ID_14 == null)) { (this.__APP_ID_14 = import21._appIdRandomProviderFactory()); }
    return this.__APP_ID_14;
  }
  get _DOCUMENT_15():any {
    if ((this.__DOCUMENT_15 == null)) { (this.__DOCUMENT_15 = import4._document()); }
    return this.__DOCUMENT_15;
  }
  get _HAMMER_GESTURE_CONFIG_16():import11.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_16 == null)) { (this.__HAMMER_GESTURE_CONFIG_16 = new import11.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_16;
  }
  get _EVENT_MANAGER_PLUGINS_17():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_17 == null)) { (this.__EVENT_MANAGER_PLUGINS_17 = [
      new import22.DomEventsPlugin(),
      new import23.KeyEventsPlugin(),
      new import11.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_16)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_17;
  }
  get _EventManager_18():import12.EventManager {
    if ((this.__EventManager_18 == null)) { (this.__EventManager_18 = new import12.EventManager(this._EVENT_MANAGER_PLUGINS_17,this.parent.get(import24.NgZone))); }
    return this.__EventManager_18;
  }
  get _DomSharedStylesHost_19():import13.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_19 == null)) { (this.__DomSharedStylesHost_19 = new import13.DomSharedStylesHost(this._DOCUMENT_15)); }
    return this.__DomSharedStylesHost_19;
  }
  get _AnimationDriver_20():any {
    if ((this.__AnimationDriver_20 == null)) { (this.__AnimationDriver_20 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_20;
  }
  get _DomRootRenderer_21():import14.DomRootRenderer_ {
    if ((this.__DomRootRenderer_21 == null)) { (this.__DomRootRenderer_21 = new import14.DomRootRenderer_(this._DOCUMENT_15,this._EventManager_18,this._DomSharedStylesHost_19,this._AnimationDriver_20,this._APP_ID_14)); }
    return this.__DomRootRenderer_21;
  }
  get _RootRenderer_22():any {
    if ((this.__RootRenderer_22 == null)) { (this.__RootRenderer_22 = import25._createConditionalRootRenderer(this._DomRootRenderer_21,this.parent.get(import25.NgProbeToken,(null as any)),this.parent.get(import9.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_22;
  }
  get _DomSanitizer_23():import15.DomSanitizerImpl {
    if ((this.__DomSanitizer_23 == null)) { (this.__DomSanitizer_23 = new import15.DomSanitizerImpl()); }
    return this.__DomSanitizer_23;
  }
  get _Sanitizer_24():any {
    if ((this.__Sanitizer_24 == null)) { (this.__Sanitizer_24 = this._DomSanitizer_23); }
    return this.__Sanitizer_24;
  }
  get _AnimationQueue_25():import16.AnimationQueue {
    if ((this.__AnimationQueue_25 == null)) { (this.__AnimationQueue_25 = new import16.AnimationQueue(this.parent.get(import24.NgZone))); }
    return this.__AnimationQueue_25;
  }
  get _ViewUtils_26():import17.ViewUtils {
    if ((this.__ViewUtils_26 == null)) { (this.__ViewUtils_26 = new import17.ViewUtils(this._RootRenderer_22,this._Sanitizer_24,this._AnimationQueue_25)); }
    return this.__ViewUtils_26;
  }
  get _IterableDiffers_27():any {
    if ((this.__IterableDiffers_27 == null)) { (this.__IterableDiffers_27 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_27;
  }
  get _KeyValueDiffers_28():any {
    if ((this.__KeyValueDiffers_28 == null)) { (this.__KeyValueDiffers_28 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_28;
  }
  get _SharedStylesHost_29():any {
    if ((this.__SharedStylesHost_29 == null)) { (this.__SharedStylesHost_29 = this._DomSharedStylesHost_19); }
    return this.__SharedStylesHost_29;
  }
  get _Title_30():import18.Title {
    if ((this.__Title_30 == null)) { (this.__Title_30 = new import18.Title()); }
    return this.__Title_30;
  }
  createInternal():import1.GLIonic2EnvConfigurationModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._GLIonic2EnvConfigurationModule_3 = new import1.GLIonic2EnvConfigurationModule();
    this._ErrorHandler_6 = import4.errorHandler();
    this._EnvConfigurationProvider_7 = new import6.EnvConfigurationProvider();
    this._APP_INITIALIZER_8 = [import1.envConfigurationFactory(this._EnvConfigurationProvider_7)];
    this._ApplicationInitStatus_9 = new import7.ApplicationInitStatus(this._APP_INITIALIZER_8);
    this._Testability_10 = new import8.Testability(this.parent.get(import24.NgZone));
    this._ApplicationRef__11 = new import9.ApplicationRef_(this.parent.get(import24.NgZone),this.parent.get(import26.Console),this,this._ErrorHandler_6,this,this._ApplicationInitStatus_9,this.parent.get(import8.TestabilityRegistry,(null as any)),this._Testability_10);
    return this._GLIonic2EnvConfigurationModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import1.GLIonic2EnvConfigurationModule)) { return this._GLIonic2EnvConfigurationModule_3; }
    if ((token === import20.LOCALE_ID)) { return this._LOCALE_ID_4; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import27.ErrorHandler)) { return this._ErrorHandler_6; }
    if ((token === import6.EnvConfigurationProvider)) { return this._EnvConfigurationProvider_7; }
    if ((token === import7.APP_INITIALIZER)) { return this._APP_INITIALIZER_8; }
    if ((token === import7.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import8.Testability)) { return this._Testability_10; }
    if ((token === import9.ApplicationRef_)) { return this._ApplicationRef__11; }
    if ((token === import9.ApplicationRef)) { return this._ApplicationRef_12; }
    if ((token === import10.Compiler)) { return this._Compiler_13; }
    if ((token === import21.APP_ID)) { return this._APP_ID_14; }
    if ((token === import28.DOCUMENT)) { return this._DOCUMENT_15; }
    if ((token === import11.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_16; }
    if ((token === import12.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_17; }
    if ((token === import12.EventManager)) { return this._EventManager_18; }
    if ((token === import13.DomSharedStylesHost)) { return this._DomSharedStylesHost_19; }
    if ((token === import29.AnimationDriver)) { return this._AnimationDriver_20; }
    if ((token === import14.DomRootRenderer)) { return this._DomRootRenderer_21; }
    if ((token === import30.RootRenderer)) { return this._RootRenderer_22; }
    if ((token === import15.DomSanitizer)) { return this._DomSanitizer_23; }
    if ((token === import31.Sanitizer)) { return this._Sanitizer_24; }
    if ((token === import16.AnimationQueue)) { return this._AnimationQueue_25; }
    if ((token === import17.ViewUtils)) { return this._ViewUtils_26; }
    if ((token === import32.IterableDiffers)) { return this._IterableDiffers_27; }
    if ((token === import33.KeyValueDiffers)) { return this._KeyValueDiffers_28; }
    if ((token === import13.SharedStylesHost)) { return this._SharedStylesHost_29; }
    if ((token === import18.Title)) { return this._Title_30; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__11.ngOnDestroy();
  }
}
export const GLIonic2EnvConfigurationModuleNgFactory:import0.NgModuleFactory<import1.GLIonic2EnvConfigurationModule> = new import0.NgModuleFactory(GLIonic2EnvConfigurationModuleInjector,import1.GLIonic2EnvConfigurationModule);